pjtest/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('users.urls'))
]

users/urls.py
from django.conf.urls import url
from . import views

app_name = 'users'

urlpatterns = [
    url(r'^$', views.UserListView.as_view(), name='user_list'),
    url(r'^detail/(?P<pk>\d+)/$', views.UserDetailView.as_view(), name='user_detail'),
]

users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.urls import reverse

from django.db import models

class User(models.Model):

    GENDER = [
        ('Male', 'Male'),
        ('Female', 'Female')
    ]

    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.EmailField()
    gender = models.CharField(max_length=20, choices=GENDER)
    ip_address = models.GenericIPAddressField()

    def __str__(self):
        return self.first_name + ' ' + self.last_name

    def get_absolute_url(self):
        return reverse('users:user_detail', args=[self.pk])

class Statistic(models.Model):
    user_id = models.ForeignKey(User, related_name='statistic', on_delete=models.CASCADE)
    date = models.DateField()
    page_views = models.IntegerField()
    clicks = models.IntegerField()

users/forms.py
from django import forms

class DateInput(forms.DateInput):
    input_type = 'date'

class UserFilterForm(forms.Form):
    from_date = forms.DateField(widget=DateInput)
    to_date = forms.DateField(widget=DateInput)

users/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db.models import Sum
from django.views.generic import ListView, DetailView, UpdateView
from datetime import datetime, timedelta

# Forms
from .forms import UserFilterForm

# Models
from .models import User


class UserListView(ListView):
    model = User
    paginate_by = 50
    template_name = 'user_list.html'

    def get_queryset(self):
        queryset = User.objects.annotate(total_clicks=Sum('statistic__clicks'),
                                         total_page_views=Sum('statistic__page_views')).order_by('id')
        return queryset


# UpdateView need for resolve 405 status error problem.
class UserDetailView(DetailView, UpdateView):
    template_name = 'user_detail.html'
    model = User
    # we don't need to DELETE method yet.
    http_method_names = ['get', 'post', 'head', 'options', 'trace']
    fields = ['first_name']

    def get_context_data(self, **kwargs):
        context = super(UserDetailView, self).get_context_data(**kwargs)
        # Default form data: 7 last days.
        default_form = {'to_date': datetime.today(), 'from_date': datetime.today() - timedelta(days=7)}
        context['form'] = UserFilterForm(default_form)
        if self.request.method == 'POST':
            f = UserFilterForm(self.request.POST)
            if f.is_valid():
                data = f.cleaned_data
                dates = []  # type: list
                clicks = []
                views = []
                dif = data['to_date'] - data['from_date']
                # create datetime range (list)
                days_range = [data['to_date'] - timedelta(days=x) for x in range(dif.days)]
                for day in days_range[::-1]:
                    total_c = (self.object.statistic.select_related('clicks').filter(date=str(day))
                        .aggregate(Sum('clicks'))['clicks__sum'])
                    total_v = (self.object.statistic.select_related('page_views').filter(date=str(day))
                        .aggregate(Sum('page_views'))['page_views__sum'])
                    clicks.append(total_c) if total_c != None else clicks.append(0)
                    views.append(total_v) if total_v != None else views.append(0)
                    dates.append("/".join([str(day.day), str(day.month)]))
                context['data'] = list(map(lambda d, c, v: (d, c, v), dates, clicks, views))  # make zip
                # set latest form data
                context['form'] = UserFilterForm({'to_date': data['to_date'], 'from_date': data['from_date']})
                return context
            else:
                return context
        else:
            return context

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- JQuery -->
	<script src="https://code.jquery.com/jquery-3.4.1.js"></script>
	<!-- BOOTSTRAP -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
	<!-- MY CSS -->
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
	{% block ed_src %}{% endblock %}
    <title>PJTest</title>
</head>
<body>
    <h1>Site Name</h1>
    {% block content %}{% endblock %}
</body>
</html>

users/templates/user_base.html
{% extends 'base.html' %}

{% block content %}
    {% block user_content %}{% endblock %}
{% endblock %}

users/templates/user_detail.html
{% extends 'user_base.html' %}

{% block ed_src %}
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
{% endblock %}

{% block user_content %}

    <a class="btn btn-success" href="{% url 'users:user_list' %}">Back to user-list</a>
    <br>
    <br>

    <form method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" />
    </form>

    <h2>User Detail</h2>

    <p>Name: {{ user.first_name }}</p>
    <p>Last name: {{ user.last_name }}</p>

    <h1>Clicks</h1>
    <canvas id="myChart"></canvas>

    <h1>Views</h1>
    <canvas id="myChart2"></canvas>


<script>
var ctx = document.getElementById('myChart').getContext('2d');
var myChart = new Chart(ctx, {
    type: 'line',
    data: {
        labels: [{% for date, clicks, views in data %}'{{ date }}', {% endfor %}],
        datasets: [{
            label: 'Clicks',
            data: [{% for date, clicks, views in data %}{{clicks}}, {% endfor %}],
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero: true
                }
            }]
        }
    }
});

var ctx = document.getElementById('myChart2').getContext('2d');
var myChart2 = new Chart(ctx, {
    type: 'line',
    data: {
        labels: [{% for date, clicks, views in data %}'{{ date }}', {% endfor %}],
        datasets: [{
            label: 'Views',
            data: [{% for date, clicks, views in data %}{{views}}, {% endfor %}],
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero: true
                }
            }]
        }
    }
});
</script>

{% endblock %}

users/templates/users/user_list.html
{% extends 'user_base.html' %}
{% load static %}

{% block user_content %}
    <p>User List</p>
	<table class="table table-sm">
	  <thead class="thead-light">
		<tr>
			<td scope="col">{{"id"|upper}}</td>
			<td scope="col">{{"first_name"|upper}}</td>
            <td scope="col">{{"last_name"|upper}}</td>
            <td scope="col">{{"email"|upper}}</td>
            <td scope="col">{{"gender"|upper}}</td>
            <td scope="col">{{"ip_address"|upper}}</td>
            <td scope="col">{{"total_clicks"|upper}}</td>
            <td scope="col">{{"total_page_views"|upper}}</td>
		</tr>
	  </thead>
        {% for user in user_list %}

            <tr>
                <td><a href="{{ user.get_absolute_url }}">{{ user.id }}</a></td>
                <td scope="row"><a href="{{ user.get_absolute_url }}">{{ user.first_name }}</a></td>
                <td><a href="{{ user.get_absolute_url }}">{{ user.last_name }}</a></td>
                <td><a href="{{ user.get_absolute_url }}">{{ user.email }}</a></td>
                <td><a href="{{ user.get_absolute_url }}">{{ user.gender }}</a></td>
                <td><a href="{{ user.get_absolute_url }}">{{ user.ip_address }}</a></td>
                <td><a href="{{ user.get_absolute_url }}">{{ user.total_clicks }}</a></td>
                <td><a href="{{ user.get_absolute_url }}">{{ user.total_page_views }}</a></td>
            </tr>

        {% endfor %}
	</table>

<!--PAGINATION-->
{% if is_paginated %}
<nav class="nav-pagination">
  <!-- FIRST -->
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
        <span class="sr-only">Previous</span>
      </a>
    </li>
    {% endif %}

    <!-- LIST -->
    {% for page in paginator.page_range %}

      {% if page == page_obj.number %}
      <li class="page-item active">
      {% else %}
      <li class="page-item">
      {% endif %}
        <a class="page-link" href="?page={{ page }}">{{ page }}</a>
      </li>

    {% endfor %}

  <!-- LAST -->
    {% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link" href="#" aria-label="Previous">
        <span aria-hidden="true">&raquo;</span>
        <span class="sr-only">Previous</span>
      </a>
    </li>
    {% endif %}
  </ul>
</nav>
{% endif %}
{% endblock %}